name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: npm install -g firebase-tools
      - run: yarn install --frozen-lockfile --immutable  
      - run: yarn install --frozen-lockfile --immutable        
        working-directory: ./src/functions

      - run: yarn lint 
      - run: yarn test

      - env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase functions:config:get --token $FIREBASE_TOKEN > .runtimeconfig.json
        working-directory: ./src/functions

      # - env:
      #     GOOGLE_CLOUD_API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}
      #   run: firebase functions:config:set translateapi.key="$GOOGLE_CLOUD_API_KEY"        

      - run: yarn e2e:ci
      - run: build:prod
